### ISSUE TITLE
Errors occur in the background view when the extension becomes active again

### ISSUE THREAD

**Issue by anickle060193** [anickle060193/easy_control#79]
The following errors occur:

``` javascript
extensions::lastError:131 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id auto_pause_enabled
    at null.callback (chrome-extension://oanebiaiakkpfipgnkpmcpkjfnclbgfi/background/background.js:510:33)reportIfUnchecked @ extensions::lastError:131
extensions::lastError:131 Unchecked runtime.lastError while running contextMenus.create: Cannot create item with duplicate id auto_pause_enabled_for_tab
    at null.callback (chrome-extension://oanebiaiakkpfipgnkpmcpkjfnclbgfi/background/background.js:519:33)reportIfUnchecked @ extensions::lastError:131
background.js:321 Port Connect: Pandora
```

**Comment by anickle060193** [comment]
It seems context menus need to be created on install instead of on start. See https://developer.chrome.com/extensions/event_pages.
